### ISSUE TITLE
The app is extraordinarily fat. Electron should be replaced with something less fat.

### ISSUE THREAD

**Issue by leenattress** [Meltress/edtk-support#3]

**Comment by leenattress** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The app is extraordinarily fat. Electron should be replaced with something less fat.](https://trello.com/c/tHyKvRJ7/8-the-app-is-extraordinarily-fat-electron-should-be-replaced-with-something-less-fat)

**Comment by M3lbz** [comment]
Moved to Tauri! less fat
